import os
import math

# サービスのURL設定
SERVICE_CAPTURE_URL = os.environ.get('SERVICE_CAPTURE_URL', 'http://service-capture:5000')
SERVICE_ESTIMATE_URL = os.environ.get('SERVICE_ESTIMATE_URL', 'http://service-estimate:5001')
SERVICE_TILE_CUT_URL = os.environ.get('SERVICE_TILE_CUT_URL', 'http://service-tile-cut:5002')
SERVICE_TILE_MERGE_URL = os.environ.get('SERVICE_TILE_MERGE_URL', 'http://service-tile-merge:5003')
SERVICE_TILE_COMPRESS_URL = os.environ.get('SERVICE_TILE_COMPRESS_URL', 'http://service-tile-compress:5004')
SERVICE_CREATE_PANEL_URL = os.environ.get('SERVICE_CREATE_PANEL_URL', 'http://service-create-panel:5005')
BACKEND_INTERNAL_URL = os.environ.get('BACKEND_INTERNAL_URL', 'http://backend:8002')
STORAGE_URL = os.environ.get('STORAGE_URL', 'http://storage')

# 環境変数からの設定
TILE_SIZE = int(os.environ.get('TILE_SIZE', '512'))

# レプリカ数の環境変数
SERVICE_CAPTURE_REPLICAS = int(os.environ.get('SERVICE_CAPTURE_REPLICAS', '2'))
SERVICE_ESTIMATE_REPLICAS = int(os.environ.get('SERVICE_ESTIMATE_REPLICAS', '2'))
SERVICE_TILE_CUT_REPLICAS = int(os.environ.get('SERVICE_TILE_CUT_REPLICAS', '4'))
SERVICE_TILE_MERGE_REPLICAS = int(os.environ.get('SERVICE_TILE_MERGE_REPLICAS', '2'))
SERVICE_TILE_COMPRESS_REPLICAS = int(os.environ.get('SERVICE_TILE_COMPRESS_REPLICAS', '2'))
SERVICE_CREATE_PANEL_REPLICAS = int(os.environ.get('SERVICE_CREATE_PANEL_REPLICAS', '1'))

# ワーカー数の設定
SERVICE_CAPTURE_WORKERS = int(os.environ.get('SERVICE_CAPTURE_WORKERS', '4'))
# その他のサービスは1レプリカあたり1ワーカー（固定）
SERVICE_ESTIMATE_WORKERS = 1
SERVICE_TILE_CUT_WORKERS = 1
SERVICE_TILE_MERGE_WORKERS = 1
SERVICE_TILE_COMPRESS_WORKERS = 1
SERVICE_CREATE_PANEL_WORKERS = 1

# 並行制御の上限値を計算（基本値 × 1.2 を繰り上げ）
CONCURRENCY_CAPTURE = math.ceil(SERVICE_CAPTURE_REPLICAS * SERVICE_CAPTURE_WORKERS * 1.2)
CONCURRENCY_ESTIMATE = math.ceil(SERVICE_ESTIMATE_REPLICAS * SERVICE_ESTIMATE_WORKERS * 1.2)
CONCURRENCY_TILE_CUT = math.ceil(SERVICE_TILE_CUT_REPLICAS * SERVICE_TILE_CUT_WORKERS * 1.2)
CONCURRENCY_TILE_MERGE = math.ceil(SERVICE_TILE_MERGE_REPLICAS * SERVICE_TILE_MERGE_WORKERS * 1.2)
CONCURRENCY_TILE_COMPRESS = math.ceil(SERVICE_TILE_COMPRESS_REPLICAS * SERVICE_TILE_COMPRESS_WORKERS * 1.2)
CONCURRENCY_CREATE_PANEL = math.ceil(SERVICE_CREATE_PANEL_REPLICAS * SERVICE_CREATE_PANEL_WORKERS * 1.2)
