source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'pg', '~> 1.5'
gem 'sequel', '~> 5.0'
gem 'httparty', '~> 0.21'
gem 'json', '~> 2.6'
gem 'rack', '~> 2.2'

group :development do
  gem 'dotenv', '~> 2.8'
end
