# frozen_string_literal: true

source "https://rubygems.org"

ruby ">= 3.1"

gem "sinatra", "~> 4.0"
gem "sinatra-contrib", "~> 4.0"

gem "puma", "~> 6.0"

gem "httparty", "~> 0.22"
gem "mini_magick", "~> 4.12"

gem "concurrent-ruby", "~> 1.2"
